Repository noverde/faster-sam, pull requests merged in 2024-02, with the labels that each got.

#99 Wip/redis
  faster_sam/cache/__init__.py
  faster_sam/cache/cache_interface.py
  faster_sam/cache/redis_cache.py
  faster_sam/middlewares/lambda_authorizer.py
  pyproject.toml
  requirements-dev.txt
  tests/test_middleware_lambda_authorizer.py
  tests/test_redis.py
Labels: enhancement

#105 feat: add rewrite path middleware
  faster_sam/middlewares/rewrite_path.py
  tests/test_middleware_rewrite_path.py
Labels: enhancement

#108 docs: update docs modules
  docs/faster_sam.adapter.rst
  docs/faster_sam.cache.rst
  docs/faster_sam.cloudformation.rst
  docs/faster_sam.middleware.rst
  docs/faster_sam.middlewares.rst
  docs/faster_sam.openapi.rst
  docs/faster_sam.routing.rst
  docs/faster_sam.rst
  docs/index.rst
Labels: documentation

#107 feat: add mapping queues
  faster_sam/adapter.py
  faster_sam/cloudformation.py
  faster_sam/lambda_event.py
  faster_sam/routing.py
  tests/fixtures/templates/example6.yml
  tests/test_adapter.py
  tests/test_lambda_event.py
  tests/test_routing.py
Labels: enhancement

#109 chore: bump faster-sam from 0.6.0 to 0.7.0
  docs/conf.py
  pyproject.toml
Labels: enhancement

#110 fix: check if resource arn is a list
  faster_sam/adapter.py
  tests/fixtures/templates/example6.yml
Labels: bug

#111 chore: bump faster-sam from 0.7.0 to 0.7.1
  docs/conf.py
  pyproject.toml
Labels: enhancement

#112 fix: cases where return is null for sqs
  faster_sam/lambda_event.py
  tests/test_routing.py
Labels: bug
