Repository noverde/faster-sam, pull requests merged in 2024-01, with the labels that each got.

#73 docs: update routing module documentation
  faster_sam/routing.py
Labels: documentation

#74 feat: add read the docs for automatic documentation
  .readthedocs.yaml
  Makefile
  docs/conf.py
  docs/index.rst
  requirements-dev.txt
Labels: documentation

#75 feat: add initial documentation configure files
  docs/faster_sam.adapter.rst
  docs/faster_sam.cloudformation.rst
  docs/faster_sam.middleware.rst
  docs/faster_sam.openapi.rst
  docs/faster_sam.routing.rst
  docs/faster_sam.rst
Labels: documentation

#76 chore: bump version from 0.1.0 to 0.2.0
  docs/conf.py
  pyproject.toml
Labels: enhancement

#77 fix: read the docs configuration file
  .readthedocs.yaml
Labels: bug

#78 fix: update the code block of openapi docstring
  faster_sam/openapi.py
Labels: documentation

#79 feat: update documentation configuration of class signature params
  docs/conf.py
Labels: documentation

#80 refactor: update class parameters of docstrings
  faster_sam/adapter.py
  faster_sam/cloudformation.py
  faster_sam/middleware.py
Labels: documentation

#83 chore: update fastapi dependency to any version
  pyproject.toml
Labels: dependencies

#82 Refactor/add middleware module
  faster_sam/middlewares/__init__.py
  faster_sam/middlewares/remove_path.py
  tests/test_middleware.py
Labels: enhancement

#86 chore: Buffer stdout and stderr during tests
  Makefile
Labels: enhancement

#85 feat: add client class
  faster_sam/middlewares/lambda_authorizer.py
  tests/test_middleware_lambda_authorizer.py
Labels: enhancement

#81 feat: add initial configuration for middleware
  faster_sam/middlewares/lambda_authorizer.py
  pyproject.toml
  requirements-dev.txt
  tests/test_middleware_lambda_authorizer.py
  tests/test_middleware_remove_path.py
Labels: enhancement

#87 chore: bump version to 0.4.0
  pyproject.toml
Labels: enhancement

#88 feat: add authorizer in context
  faster_sam/routing.py
  tests/test_routing.py
Labels: enhancement

#89 feat: improve credentials
  faster_sam/middlewares/lambda_authorizer.py
  faster_sam/web_identity_providers.py
  pyproject.toml
  requirements-dev.txt
  tests/test_middleware_lambda_authorizer.py
  tests/test_web_identity_providers.py
Labels: enhancement

#90 chore: bump version to 0.5.0
  pyproject.toml
Labels: enhancement

#91 fix: error using upper to get environment variables
  faster_sam/middlewares/lambda_authorizer.py
  tests/test_middleware_lambda_authorizer.py
Labels: enhancement

#93 feat: improve tests credentials
  tests/test_middleware_lambda_authorizer.py
Labels: enhancement
